-- Add GST/tax fields to sales_orders and quotations for parity with invoices

ALTER TABLE sales_orders
  ADD COLUMN IF NOT EXISTS gst_type      VARCHAR(20)    NOT NULL DEFAULT 'intra_state',
  ADD COLUMN IF NOT EXISTS tax_type      VARCHAR(20)    NOT NULL DEFAULT 'exclusive',
  ADD COLUMN IF NOT EXISTS is_interstate BOOLEAN        NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS subtotal      NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst          NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst          NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst          NUMERIC(15,2)  NOT NULL DEFAULT 0;

ALTER TABLE sales_order_items
  ADD COLUMN IF NOT EXISTS discount NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst     NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst     NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst     NUMERIC(15,2) NOT NULL DEFAULT 0;

ALTER TABLE quotations
  ADD COLUMN IF NOT EXISTS gst_type      VARCHAR(20)    NOT NULL DEFAULT 'intra_state',
  ADD COLUMN IF NOT EXISTS tax_type      VARCHAR(20)    NOT NULL DEFAULT 'exclusive',
  ADD COLUMN IF NOT EXISTS is_interstate BOOLEAN        NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS subtotal      NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst          NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst          NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst          NUMERIC(15,2)  NOT NULL DEFAULT 0;

ALTER TABLE quotation_items
  ADD COLUMN IF NOT EXISTS discount NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cgst     NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sgst     NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst     NUMERIC(15,2) NOT NULL DEFAULT 0;
